# Generated by Django 3.2.1 on 2021-05-07 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_url', models.URLField(null=True, verbose_name='url 값')),
                ('input_image', models.ImageField(null=True, upload_to='')),
                ('site', models.CharField(choices=[('naver', 'NAVER'), ('g-market', 'G-MARKET'), ('coupang', 'COUPANG')], default='naver', max_length=12)),
                ('registered_dttm', models.DateTimeField(auto_now=True, null=True, verbose_name='등록시간')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcuser.fcuser', verbose_name='사용자')),
            ],
        ),
    ]
