# Generated by Django 3.2.1 on 2021-05-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fcuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='비밀번호')),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'table_user',
            },
        ),
    ]
