# Generated by Django 3.1.7 on 2021-05-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='상품명')),
                ('price', models.IntegerField(null=True, verbose_name='상품가격')),
                ('description', models.TextField(null=True, verbose_name='상품설명')),
                ('stock', models.IntegerField(null=True, verbose_name='재고')),
                ('congestion', models.IntegerField(default=0, null=True, verbose_name='강의실 혼잡도')),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'fastcampus_product',
            },
        ),
    ]
